export const SITE = {
  name: "Implantik by Dr. Chirap",
  shortName: "Implantik",
  domain: "implantik.ro",
  url: "https://implantik.ro",
  phone: "[TELEFON CLINICĂ]",
  phoneHref: "tel:+40000000000",
  whatsapp: "[NUMĂR WHATSAPP]",
  whatsappHref: "https://wa.me/40000000000",
  email: "contact@implantik.ro",
  address: "[ADRESĂ]",
  addressLocality: "Iași",
  addressCountry: "RO",
  postalCode: "[COD POȘTAL]",
  geo: { latitude: 47.1585, longitude: 27.6014 },
  hours: "[PROGRAM]",
  openingHours: ["Mo-Fr 09:00-18:00", "Sa 09:00-14:00"],
  priceRange: "$$",
  gtmId: process.env.NEXT_PUBLIC_GTM_ID ?? "[GTM_ID]",
  gtmServerUrl: process.env.NEXT_PUBLIC_GTM_SERVER_URL ?? "[GTM_SERVER_URL]",
  ga4Id: process.env.NEXT_PUBLIC_GA4_ID ?? "[GA4_ID]",
  metaPixelId: process.env.NEXT_PUBLIC_META_PIXEL_ID ?? "[META_PIXEL_ID]",
  metaCapiToken: "[META_CAPI_TOKEN]",
  tiktokPixelId: process.env.NEXT_PUBLIC_TIKTOK_PIXEL_ID ?? "[TIKTOK_PIXEL_ID]",
  tiktokEventsToken: "[TIKTOK_EVENTS_TOKEN]",
  googleRating: "[RATING REAL]",
  googleProfileUrl: "[URL PROFIL GOOGLE — DE CONFIRMAT]",
  social: {
    handle: "@implantikbydrchirap",
    facebook: "https://www.facebook.com/implantikbydrchirap",
    instagram: "https://www.instagram.com/implantikbydrchirap",
    tiktok: "https://www.tiktok.com/@implantikbydrchirap",
  },
} as const;

export const PLACEHOLDERS = {
  logo: "[LOGO DE ADĂUGAT]",
  photo: "[POZĂ REALĂ DE ADĂUGAT]",
  stat: "[CIFRĂ REALĂ, DOVEDIBILĂ — DE CONFIRMAT]",
  beforeAfter: "[CAZ PROPRIU + CONSIMȚĂMÂNT PACIENT]",
  bio: "[BIO + TITLURI/COMPETENȚE Dr. Chirap]",
  prices: "[PREȚURI — DE CONFIRMAT]",
} as const;
