export const scaffoldPages = [
  { slug: "implant-all-on-4-iasi", titleRo: "Implant All-on-4 Iași", titleEn: "All-on-4 Implants Iași" },
  { slug: "sinus-lift-iasi", titleRo: "Sinus Lift Iași", titleEn: "Sinus Lift Iași" },
  {
    slug: "reabilitari-complexe",
    titleRo: "Reabilitări complexe",
    titleEn: "Complex rehabilitations",
    descRo: "Chirurgie orală și maxilo-facială pentru cazuri complexe.",
    descEn: "Oral and maxillofacial surgery for complex cases.",
  },
  { slug: "chirurgie-orala", titleRo: "Chirurgie orală", titleEn: "Oral surgery" },
  {
    slug: "estetica-faciala",
    titleRo: "Estetică facială",
    titleEn: "Facial aesthetics",
    descRo: "Servicii de estetică facială (acid hialuronic, toxina botulinică) — informații pentru pacient.",
    descEn: "Facial aesthetic services (hyaluronic acid, botulinum toxin) — patient information.",
  },
  { slug: "estetica-dentara", titleRo: "Estetică dentară", titleEn: "Dental aesthetics" },
  { slug: "ortodontie", titleRo: "Ortodonție", titleEn: "Orthodontics" },
  { slug: "stomatologie", titleRo: "Stomatologie", titleEn: "General dentistry" },
  {
    slug: "turism-dentar",
    titleRo: "Turism dentar",
    titleEn: "Dental tourism",
    descRo: "Plan de tratament personalizat și logistică pentru pacienți naționali și internaționali.",
    descEn: "Personalized treatment plan and logistics for national and international patients.",
  },
  { slug: "preturi", titleRo: "Prețuri transparente", titleEn: "Transparent pricing" },
  { slug: "echipa", titleRo: "Echipa", titleEn: "Our team" },
  {
    slug: "cazuri-clinice",
    titleRo: "Cazuri clinice",
    titleEn: "Clinical cases",
    descRo: "Cazuistică proprie, cu consimțământul pacienților.",
    descEn: "Own case studies, with patient consent.",
  },
  { slug: "ghiduri", titleRo: "Ghiduri", titleEn: "Guides" },
] as const;
